apiVersion: v1
kind: Service
metadata:
  name: todo-app-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: todo-app
  ports:
    - protocol: TCP
      port: 80 # Puerto donde se expondrá el servicio
      targetPort: 3000 # Puerto interno del contenedor
