apiVersion: v1
kind: ConfigMap
metadata:
  name: todo-app-config
data:
  NODE_ENV: production
  PORT: "3000"
  DB_HOST: "postgres"
  DB_USER: "postgres"
  DB_PASSWORD: "postgres"
  DB_PORT: "5432"
  DB_NAME: "todos_db"
